# change to mode: prod before generating for production files
# change to mode: dev before generating for development files
mode: dev
# Relative path from content folder.
media_root: media
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: Liang Zou Photography, LiangZou Photography
        author:
            name: Liang Zou
            url: "http://liangzouphotography.com"
        home_url: /index.html
        google_drive_dir: "http://bookmarkmgr.appspot.com/static/images/lzp"
        menu:
            - title: Home
              url: /index.html
            - title: Weddings
              url: /weddings\index.html
              submenu:
                - title: Frank & Tina
                  url: /weddings/frank-tina.html
            - title: Family
              url: /family\index.html
              submenu:
                - title: Family 1
                  url: /family/family-1.html
                - title: Family 2
                  url: /family/family-2.html
                - title: Family 3
                  url: /family/family-3.html
                - title: Family 4
                  url: /family/family-4.html
                - title: Family 5
                  url: /family/family-5.html
            - title: Portrait
              url: /portrait\index.html
              submenu:
                - title: Portrait 1
                  url: /portrait/portrait-1.html
                - title: Portrait 2
                  url: /portrait/portrait-2.html
                - title: Portrait 3
                  url: /portrait/portrait-3.html
                - title: Portrait 4
                  url: /portrait/portrait-4.html
                - title: Portrait 5
                  url: /portrait/portrait-5.html
                - title: Portrait 6
                  url: /portrait/portrait-6.html
            - title: Maternity
              url: /maternity\index.html
              submenu:
                - title: Vivien R
                  url: /maternity/vivien.html
                - title: Belly Painting
                  url: /maternity/belly-painting.html
                - title: Mama Group
                  url: /maternity/mama-group.html
            - title: Newborn
              url: /newborn\index.html
              submenu:
                - title: Kyle L
                  url: /newborn/kyle.html
                - title: Fiona Z
                  url: /newborn/fiona.html
                - title: Rella W
                  url: /newborn/rella.html
                - title: James
                  url: /newborn/james.html
                - title: Brian
                  url: /newborn/brian.html
            - title: Events
              url: /events\index.html
            - title: Real Estate
              url: /real-estate\index.html
            - title: Architecture
              url: /architecture.html

deploy_root: ../zoukyle.github.io
